name: master-push

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os_name: Linux_x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: prman-Linux-x86_64.tar.gz
            executable: rpi_pr
          
          - os_name: Windows_x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            name: prman-Windows-x86_64.tar.gz
            executable: rpi_pr.exe
      
    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain if not cross compiling
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.platform.target }}

    - name: Compile for Generic Linux
      shell: bash
      run: cargo build --release --target ${{ matrix.platform.target }}
      if: ${{ !contains(matrix.platform.os, 'windows') }}
    
    - name: Compile for Windows x86_64
      shell: powershell
      run: cargo build --release --target ${{ matrix.platform.target }}
      if: ${{ contains(matrix.platform.os, 'windows') }}

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform.name }}
        path: ./target/release/${{ matrix.platform.executable }}